name: remote_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^2.0.1
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  # Number formatting
  intl: ">=0.14.0"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/placeholder_img.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
